### ISSUE TITLE
html file infinite loading

### ISSUE THREAD

**Issue by evilsh3ll** [homeisfar/LinuxDir2HTML#6] opened 2021-12-24 10:27 UTC
Hello I installed linuxdir2html from pip in archlinux. It correctly generates the html file (with all folders) in some paths but it generates an html file empty (with the correct number of files in the top left of the page) for some other paths.
![image](https://user-images.githubusercontent.com/63223659/147344737-db350337-6743-48d0-bf73-c3d33e66ee9e.png)
This is not a problem of javascript because I opened it on a vanilla browser, and because some paths works, other not. Anyway I'm using it to scan full hard disk (full root path, ~10-15TB)

**Comment by homeisfar** [comment] 2022-10-27 20:02
Assuming this was caused by double quotes in a file's name, this is fixed in the latest release. Some additional comments: https://github.com/homeisfar/LinuxDir2HTML/issues/7#issuecomment-1293955842

**Closed by homeisfar** 2022-10-27 20:02 UTC
